spring:
  datasource:
    url: ${DB_URL:jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
    driver-class-name: ${DB_DRIVER:org.h2.Driver}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: ${JPA_DIALECT:org.hibernate.dialect.H2Dialect}
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      encoding: UTF-8

  flyway:
    enabled: ${FLYWAY_ENABLED:false}

jwt:
  secret: ${JWT_SECRET:dGhpcy1pcy1hLXN1cGVyLXNlY3JldC1rZXktZm9yLWxvY2FsLWRldmVsb3BtZW50LTMyLWJ5dGVzLXVzZWQ=}
  expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:3600000}

portone:
  bypass-verification: true
  base-url: "https://api.portone.io"
  api-secret: ${PORTONE_API_SECRET:}
  store-id: ${PORTONE_STORE_ID:}
  channel-key: ${PORTONE_CHANNEL_KEY:}
  billing-channel-key: ${PORTONE_BILLING_CHANNEL_KEY:}
  connect-timeout: ${PORTONE_CONNECT_TIMEOUT:2s}
  read-timeout: ${PORTONE_READ_TIMEOUT:5s}
  webhook:
    secret: ${PORTONE_WEBHOOK_SECRET:}
