spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    web:
      pageable:
        one-indexed-parameters: true

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: false     # 운영 환경 성능 및 보안을 위해 SQL 로그 출력 비활성화
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: false

  sql:
    init:
      mode: never       # 운영 환경에서는 data.sql 실행 방지

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}

portone:
  base-url: "https://api.portone.io"
  api-secret: ${PORTONE_API_SECRET}
  store-id: ${PORTONE_STORE_ID}
  channel-key: ${PORTONE_CHANNEL_KEY}
  billing-channel-key: ${PORTONE_BILLING_CHANNEL_KEY}
  connect-timeout: ${PORTONE_CONNECT_TIMEOUT}
  read-timeout: ${PORTONE_READ_TIMEOUT}
  webhook:
    secret: ${PORTONE_WEBHOOK_SECRET}
