spring:
  application:
    name: sparta-payment-system

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    web:
      pageable:
        one-indexed-parameters: true

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: never  # 운영/공용 환경에서는 data.sql 자동 실행 방지

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

server:
  port: 8080

# JWT 설정
jwt:
  secret: ${JWT_SECRET} # Base64 encoded
  expiration: ${JWT_ACCESS_TOKEN_EXPIRATION} # 1시간 (ms)

portone:
  base-url: "https://api.portone.io"
  api-secret: ${PORTONE_API_SECRET}
  store-id: ${PORTONE_STORE_ID}
  channel-key: ${PORTONE_CHANNEL_KEY}
  webhook-secret: ${PORTONE_WEBHOOK_SECRET}

---
spring:
  config:
    activate:
      on-profile: local
  sql:
    init:
      mode: always  # local 환경에서만 샘플 데이터(data.sql) 실행