spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/commerce_payment}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: false

  sql:
    init:
      mode: always

jwt:
  secret: ${JWT_SECRET:c29tZXRlc3RzZWNyZXRrZXlmb3Jqd3R0b2tlbnByb3ZpZGVyc29tZXRlc3RzZWNyZXRrZXk=}
  expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:3600000}

portone:
  base-url: "https://api.portone.io"
  api-secret: ${PORTONE_API_SECRET:test_api_secret}
  store-id: ${PORTONE_STORE_ID:test_store_id}
  channel-key: ${PORTONE_CHANNEL_KEY:test_channel_key}
  connect-timeout: ${PORTONE_CONNECT_TIMEOUT:2s}
  read-timeout: ${PORTONE_READ_TIMEOUT:5s}
  webhook:
    secret: ${PORTONE_WEBHOOK_SECRET:test_webhook_secret}
